### ISSUE TITLE
SafeSEH reporting "False" when it is not

### ISSUE THREAD

**Issue by bjwallwin** [NetSPI/PESecurity#11]
I am running PESecurity against an EXE that has /SAFESEH set in its linker options, however when I run PESecurity against the EXE its reporting SafeSEH=False.  If I run BinSkim, or BinScope it detects its set correctly?

**Comment by egru** [comment]
Thanks. I'll take a look at it.

**Comment by egru** [comment]
pesecurity should have the same checks for safeseh as binskim and other tools
