### ISSUE TITLE
Window exe's SafeSEH is always false no matter the linker option is set or not from VS2019

### ISSUE THREAD

**Issue by DengYiming** [NetSPI/PESecurity#23]
Pls see the following code, it seems like Get-SEHStatus is never executed?
    if ($ARCH -eq 'AMD64')
    {
      $SEH = 'N/A'
    }
    elseif ($ARCH -ne 'AMD64')
    {
      $HighentropyVA = 'N/A'
    }
    elseif ($SEH -ne 'N/A')
    {
      #Get SEH Status
      $SEH = Get-SEHStatus $CurrentFile $NTHeader $PointerNtHeader $PEBaseAddr

    }

**Comment by egru** [comment]
You are absolutely correct. Thanks for catching that. I changed both elseifs to if statements.
